# =============================================================================
# R/mod_profile_header.R — Tab 5: Nested Modules (Inner: Demographics Header)
# =============================================================================
# Purpose: An INNER module called by mod_patient_profile (the outer module).
#          Displays a demographics summary card for a selected patient.
#
# Key teaching points:
#   1. This is a standard module — it has no awareness that it is "inner."
#      The nesting is achieved by the OUTER module calling this module's UI
#      and server functions, wrapping the ID with its own ns().
#   2. Data is passed as a reactive argument. The outer module passes a
#      reactive expression for the selected patient's demographics row;
#      this inner module calls it with parentheses to get the current value.
#   3. Inner modules receive data already filtered by the outer module —
#      they do not re-filter or re-select. This is the correct layering:
#      outer handles selection, inners handle display.
#
# Created: 2026-06-18
# =============================================================================

#' Patient Profile Header — UI
#'
#' Renders a card displaying key demographics for one patient. Called inside
#' \code{mod_patient_profile_ui()} with a namespaced ID.
#'
#' @param id Character scalar. Module namespace ID (typically
#'   the outer module's ns("header")).
#'
#' @return A \code{card} tag object.
#'
#' @export
mod_profile_header_ui <- function(id) {
  ns <- NS(id)

  card(
    card_header("Demographics"),
    # uiOutput renders dynamic content generated by the server.
    # A fixed layout would fail when no patient is selected.
    uiOutput(ns("header_content"))
  )
}

#' Patient Profile Header — Server
#'
#' Renders demographics content for the patient whose data is supplied via
#' the \code{patient_data} reactive argument.
#'
#' @param id Character scalar. Module namespace ID.
#' @param patient_data A reactive expression returning a single-row data frame
#'   of ADSL data for the selected patient, or an empty data frame if none.
#'
#' @return Nothing. Side effects only (output rendering).
#'
#' @export
mod_profile_header_server <- function(id, patient_data) {
  # --- Validate inputs --- [2026-06-18]
  if (!is.reactive(patient_data)) {
    stop("`patient_data` must be a reactive expression.", call. = FALSE)
  }

  moduleServer(id, function(input, output, session) {

    # --- Render demographics content --- [2026-06-18]
    # patient_data() is called with parentheses — reads the reactive value.
    # req() halts rendering when the data frame is empty (no patient selected).
    output$header_content <- renderUI({
      pt <- patient_data()
      req(nrow(pt) > 0)

      layout_columns(
        col_widths = c(3, 3, 3, 3),
        value_box(title = "Age",     value = pt$AGE,     theme = "secondary"),
        value_box(title = "Sex",     value = pt$SEX,     theme = "secondary"),
        value_box(title = "Race",    value = pt$RACE,    theme = "secondary"),
        value_box(title = "Country", value = pt$COUNTRY, theme = "secondary")
      )
    })
  })
}
