# =============================================================================
# R/mod_dynamic_card.R — Tab 6: Dynamic Modules (Per-Instance Card)
# =============================================================================
# Purpose: Defines a module that is instantiated multiple times at runtime by
#          mod_dynamic_host. Each instance is a self-contained card showing
#          a filtered AE view for a user-selected ARM, plus a remove button.
#
# Key teaching points:
#   1. This module is completely standard. It has no knowledge that it is
#      "dynamic." The dynamic behavior (creating/removing instances) is handled
#      entirely by the HOST module (mod_dynamic_host).
#   2. Each instance gets a UNIQUE id (e.g., "card_1", "card_2"). Unique IDs
#      prevent namespace collisions. The host generates these IDs using a
#      counter pattern: id <- paste0("card_", counter).
#   3. The "Remove" button inside this card outputs a value that the HOST
#      module observes. To communicate the remove action back to the host,
#      the button value is returned from moduleServer() — the host checks it.
#   4. The UI for each instance is rendered via insertUI() in the host module.
#      The server is called immediately after insertUI() to register the
#      reactive bindings. Order matters: insertUI() first, then the server call.
#
# Created: 2026-06-18
# =============================================================================

#' Dynamic AE Comparison Card — UI
#'
#' Renders a single card with an ARM selector and AE table for one dynamic
#' module instance. Called inside \code{insertUI()} by the host module.
#'
#' @param id Character scalar. A unique ID for this module instance,
#'   generated by the host (e.g., "card_1").
#'
#' @return A \code{card} tag object.
#'
#' @export
mod_dynamic_card_ui <- function(id) {
  ns <- NS(id)

  card(
    # --- Card header with remove button --- [2026-06-18]
    # The remove button is inside the card header. Its ID is namespaced so
    # each instance has a unique "remove" input (e.g., "card_1-remove").
    card_header(
      class = "d-flex justify-content-between align-items-center",
      paste("Comparison:", id),
      actionButton(
        inputId = ns("remove"),
        label   = "Remove",
        class   = "btn btn-sm btn-outline-danger"
      )
    ),

    # --- ARM filter for this card instance --- [2026-06-18]
    # Each card has its OWN ARM selector — independent of other cards and of
    # the host module's state. This is the value of dynamic modules: each
    # instance maintains its own independent state.
    selectInput(
      inputId  = ns("arm"),
      label    = "Treatment Arm",
      choices  = c("All", "Placebo", "Drug A 10mg", "Drug A 20mg"),
      selected = sample(c("Placebo", "Drug A 10mg", "Drug A 20mg"), 1)
    ),

    # --- AE count display --- [2026-06-18]
    tags$p(
      tags$strong("AE count: "),
      textOutput(ns("ae_count"), inline = TRUE)
    ),

    DTOutput(ns("ae_table"))
  )
}

#' Dynamic AE Comparison Card — Server
#'
#' Filters \code{adae} by the ARM selected in this card instance and renders
#' a DT table. Returns a reactive that signals "TRUE" when the Remove button
#' is clicked — the host module observes this to destroy the instance.
#'
#' @section Remove button pattern:
#' The card cannot remove itself — it does not know about \code{insertUI} or
#' \code{removeUI}. Instead it returns a reactive that fires when the remove
#' button is clicked. The host module observes this reactive and calls
#' \code{removeUI()} and cleans up state. This keeps the card module clean
#' and reusable.
#'
#' @param id Character scalar. Unique instance ID.
#' @param adae Data frame. Full adverse events dataset.
#'
#' @return A reactive expression that returns \code{TRUE} once the Remove
#'   button has been clicked (specifically, returns the button click count > 0).
#'
#' @export
mod_dynamic_card_server <- function(id, adae) {
  # --- Validate inputs --- [2026-06-18]
  if (!is.data.frame(adae)) {
    stop("`adae` must be a data frame.", call. = FALSE)
  }

  moduleServer(id, function(input, output, session) {

    # --- Filtered AE reactive for this card --- [2026-06-18]
    filtered_ae <- reactive({
      req(input$arm)
      if (input$arm == "All") {
        adae
      } else {
        adae %>% filter(ARM == input$arm)
      }
    })

    # --- AE count output --- [2026-06-18]
    output$ae_count <- renderText({
      nrow(filtered_ae())
    })

    # --- AE table for this card --- [2026-06-18]
    output$ae_table <- renderDT({
      datatable(
        filtered_ae() %>%
          select(USUBJID, AEDECOD, AESEV, AESER) %>%
          head(50),
        options  = list(pageLength = 5, scrollX = TRUE),
        rownames = FALSE
      )
    })

    # --- Return remove signal --- [2026-06-18]
    # The host module will observe this reactive. When input$remove > 0,
    # it means the Remove button has been clicked at least once, and the
    # host should destroy this instance. Returning a reactive (not a plain
    # value) ensures the host's observer fires reactively when the button
    # is clicked.
    reactive({ input$remove > 0 })
  })
}
